### ISSUE TITLE
[Bug]: BucketLib crashes under Forge 47.1.0 (Recommended version)

### ISSUE THREAD

**Issue by Sinhika** [cech12/BucketLib#26]
### Minecraft Version

1.20.1

### Forge Version

1.20.1-47.1.0

### Mod Version

1.20.1-2.2.0.0

### Modpack or other Mod

I am developing the 1.20.1 port of SimpleOres2.  This crash happened repeatedly and consistently while running client in the Eclipse IDE.

### Describe the Issue

I fly around--or login in the crash region--and get the crash shown in the crash log (Gist link provided). Based on the exception thrown and the classes involved, I'd guess that your mixin affecting axolotl AI does not play well with whatever changes Forge has made to axolotl AI as of 47.1.0. As that is the current recommended version, and I need bucketLib to implement my copper buckets in SimpleOres2, I'd appreciate it if bucketLib worked with Forge 1.20.1-47.1.0.

### Logs

https://gist.github.com/Sinhika/12532325824723f6f6cbc734fb797e02

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No.

**Comment by cech12** [comment]
Hey @Sinhika,

Did you add the two mixin related lines to your gradle file? 
https://github.com/cech12/BucketLib/wiki/Developer-Guide#since-bucketlib-1193-1200

Maybe this is the issue, because I cannot reproduce it. Could you send me your seed and the location where the crash happens?

Thanks for your report.

**Comment by cech12** [comment]
@Sinhika 
By the way, why are you adding BucketLib as jar-in-jar?
It would be great for BucketLib updates and compatibility with mods like Wooden and Ceramic Bucket, when it is not included in your jar.
Greetings :)

**Comment by Sinhika** [comment]
Ah, that may be it. I was porting directly from 1.19.2 to 1.20.1, and did not realize there had been a change in how to configure it. I'll get back to you the next time I work on it.

I did jar-in-jar so I didn't have to add it as Yet Another Required Lib for users to download.  why would it be a compatibility problem with other bucket mods? Jar-in-Jar is designed to negotiate with other mods to find the most compatible version of the dependency, avoiding the problem of older methods of embedding dependencies.

**Comment by cech12** [comment]
Okay, it would be great if you let me know, if this was the issue here. :)

Ah ok, I never used jar-in-jar. Then it may be not an compatibility problem with other mods using the same library in another version. :) But when I fix bugs in my mod, you have to update your mod everytime to add my mods jar to your mods jar. So, a looser dependency could be more useful as such an including one. Downloading a single file is not that complicated in times of Minecraft launchers and automatic updates.^^

I saw, that your 1.19.2 mod included BucketLib 1.19-1.0.3.0. Since then multiple bugs and compatibility issues where fixed, that users of your mod may not download because of the jar-in-jar. Bugs like rendering issues and problems with waterlogging were fixed as well as compatibility enhancements were made with Naturalist, The Undergarden and Farmers Delight.

Maybe you think about that and decide to use a looser dependency to benefit from such bugfixes and enhancements in the next 1.20 version of your mod. :)

**Comment by Sinhika** [comment]
Good point. Yes, the missing mixin lines in build.gradle were the problem. Works fine, now, though I do have a couple of cosmetic bugs to report. This bug, however, you can close.

**Comment by cech12** [comment]
Thanks for your feedback! :)
