### ISSUE TITLE
[Feature]: Custom stack for bucket with fluid in it

### ISSUE THREAD

**Issue by Byllfighter** [cech12/BucketLib#37]
### Describe the Feature

Add ability to set custom item stack limit for bucket with same fluid

**Comment by cech12** [comment]
@Byllfighter This is a really special wish that differs a lot from vanilla. Do you have any concrete usecase for this?

**Comment by Byllfighter** [comment]
I wanted to make a mod, that adds sponge that can contain a fluid and can be stackable.

**Comment by cech12** [comment]
Sounds really interesting! For which version you want to create this mod? I develop new features only for the latest Minecraft version. (1.20.4) If the changes are small enough, I could backport them to 1.20.1.

**Comment by Byllfighter** [comment]
I planned to make this mod for 1.20.1, and then port it to 1.20.4.

**Comment by cech12** [comment]
I'm sorry to disappoint you, but unfortunately Minecraft is not designed to make container items stackable. Unfortunately, there is no way in the vanilla crafting system to remove the empty containers from the crafting grid if they are stacked. Therefore, unfortunately I cannot implement the feature here. Unfortunately, it cannot be forbidden to only allow stacks with a size of 1 in the crafting grid, as the caching here is very strange. :/
But I think, this library mod is not really made for your usecase, because of all the bucket special cases, that should not affect your sponges (dispense behavior, rightclick behaviour, milk drinking, ...)
I hope you find a way without my library :)
