### ISSUE TITLE
[Bug]: When I press E to open inventory then game crashed

### ISSUE THREAD

**Issue by PhilTheGreatLOL** [cech12/BucketLib#45]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Mod Loader Version

Forge

### Mod Version

1.20.1-2.3.4.1

### Modpack or other Mod

None or Unknown

### Describe the Issue

In creative mode, When I decided to open Inventory by press E but an unexpected error occurred then crash into desktop, Can you fix with that?

### Logs

[crash-2024-08-24_00.29.45-client.txt](https://github.com/user-attachments/files/16732023/crash-2024-08-24_00.29.45-client.txt)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Nothing

**Comment by cech12** [comment]
Thanks for your report! Seems to be a compatibility issue with Quark or HerbalBrews. I will look into that when I have time.

**Comment by cech12** [comment]
@PhilTheGreatLOL Which mod is adding the item "mint_green_tea_bucket" or a "mint_green_tea" fluid?

**Comment by PhilTheGreatLOL** [comment]
![Screenshot (50)](https://github.com/user-attachments/assets/17d63014-4055-42c5-a6bc-63a432eb5433)
It's Respiteful addon which I use with Farmer's Respite, Sir
https://www.curseforge.com/minecraft/mc-mods/respiteful

**Comment by cech12** [comment]
@PhilTheGreatLOL Thanks for your quick answer. Some research has shown, that you already opened an issue at the corresponding repository:
https://github.com/DragonsPlusMinecraft/Respiteful/issues/23

It seems that the generated tea fluids of Respiteful try to return an item called "<fluidname>_bucket". This item does not exist. The same issue seems to occur in other mods as well:
- https://github.com/DragonsPlusMinecraft/Respiteful/issues/21
- https://github.com/DragonsPlusMinecraft/Respiteful/issues/20
- ...

The fluids are generated with a library, which "supports" fluids without buckets by calling a method `nobucket()`, that is also called:
https://github.com/DragonsPlusMinecraft/Respiteful/blob/660d4480dfe74a0a2e617c4858ea7a9b792b01ce/src/main/java/plus/dragons/respiteful/entries/RespitefulFluids.java#L113

This library is Registrate (tterag1098) and there is already a PR which should fix that issue:
https://github.com/tterrag1098/Registrate/pull/55
But nothing happens since a year. 

So the only thing I can say to you: BucketLib is not compatible with Respiteful since Respiteful is registering the fluids differently or the bug is fixed in Registrate.

**Comment by cech12** [comment]
I added a workaround for the game crash by catching the specific exception that is thrown in this scenario for BucketLib in the upcoming versions:
- 1.20.1-2.3.4.2
- 1.20.4-3.2.1.4
- 1.20.6-3.3.0.8
- 1.21-4.1.0.1

But the fluids are not compatible with BucketLib and the log will show related error messages. I highly recommend to not use Respiteful in combination with other mods that are dealing with fluids (Thermal Foundation, Create, ...) until the related issues of Respiteful (https://github.com/DragonsPlusMinecraft/Respiteful/issues/23) and/or Registrate (https://github.com/tterrag1098/Registrate/issues/69) are fixed.
